language: python
python:
    - nightly
    - 3.6
    - 3.5
install:
    - pip install -r requirements.txt
    - pip install -r dev_requirements.txt
    - pip install .
script: 
    - coverage run --source=lockchain setup.py nosetests
after_success: coveralls
